packages:
  - 'packages/*'

catalog:
  "@ai-sdk/anthropic": "^1.2.0"
  "@ai-sdk/openai": "^1.3.0"
  "@types/node": "^20.10.0"
  "ai": "^4.2.0"
  "dotenv": "^16.4.7"
  "eslint": "^8.57.0"
  "jest": "^29.7.0"
  "prettier": "^3.2.5"
  "ts-jest": "^29.1.2"
  "typescript": "^5.8.2"
  "uuid": "^11.1.0"
  "zod": "^3.24.2"
